### ISSUE TITLE
Integrate Mailchimp API with website

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/octopusthink.com#56]
Newsletters are a great way of keeping people top-of-mind. (I don't have stats at hand, but I know marketers love them and get a lot of value from them.) We should probably have one, but I'm wary of signing myself up for more work. 

Maybe we could do a bi-monthly or quarterly cadence, showing highlights from the blog and/or what we're currently working on? Thoughts?

**Comment by tofumatt** [comment]
We've set this up now, and I think that's all there is for this issue! We can chat about what content we want to include elsewhere, but since it's not really related to the site, we can close this for now.

(It might be worth having an us-hosted version of the newsletter content on the site, but dunno about that! It could be a separate issue though.)

**Comment by sarahmonster** [comment]
Fair enough! Right now the signup form on the website is a wee bit fragile (ie, it just uses a POST directly), so we'll want to replace it with a better implementation. I started this in #62 but got stuck and couldn't really move forward at all. 

I'm going to re-open this with a title that better reflects what we actually need here, and move it to the post-launch milestone, because it isn't super important right now.

Long-term, what we'll want is:
- a signup form that interfaces directly with the Mailchimp API for stuff like error handling &  whatnot
- the ability to add a checkbox to the contact form (and potentially others) to automatically subscribe someone
